services:
  nextcloud:
    image: ${IMAGES_PREFIX}-app
    restart: always
    volumes:
      - php_socket:/var/run/php
      - ./app-hooks:/docker-entrypoint-hooks.d
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./nextcloud:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-!ChangeMe!}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - NEXTCLOUD_DEFAULT_PHONE_REGION=${NEXTCLOUD_DEFAULT_PHONE_REGION}
      - NEXTCLOUD_MAINTENANCE_WINDOW_START=${NEXTCLOUD_MAINTENANCE_WINDOW_START}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      # Envs used once during the installation
      - OVERWRITECLIURL=${OVERWRITECLIURL:-http://localhost}
      - OVERWRITEPROTOCOL=${OVERWRITEPROTOCOL:-http}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      # Uncomment the following lines to create an admin account. It works only
      #  for fresh installations.
      #- NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      #- NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-!ChangeMe!}

  nginx:
    build:
      context: ./docker/nginx
    image: ${IMAGES_PREFIX}-www
    restart: always
    ports:
      - ${NEXTCLOUD_HOST:-127.0.0.1}:${NEXTCLOUD_PORT:-80}:80
    volumes:
      - php_socket:/var/run/php
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./nextcloud:/var/www/html
    depends_on:
      - nextcloud

  db:
    build:
      context: ./docker/db
    image: ${IMAGES_PREFIX}-database
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-!ChangeMe!}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
      - MYSQL_USER=${MYSQL_USER:-nextcloud}

  redis:
    build:
      context: ./docker/redis
    image: ${IMAGES_PREFIX}-redis
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}

volumes:
  php_socket:
