services:
  nextcloud:
    restart: always
    volumes:
      - php_socket:/var/run/php
      - ./app-hooks:/docker-entrypoint-hooks.d
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./nextcloud:/var/www/html
    depends_on:
      - db
      - redis
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}

  nginx:
    build:
      context: ./docker/nginx
    restart: always
    ports:
      - ${NEXTCLOUD_HOST:-127.0.0.1}:${NEXTCLOUD_PORT:-80}:80
    volumes:
      - php_socket:/var/run/php
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./nextcloud:/var/www/html
    depends_on:
      - nextcloud

  db:
    build:
      context: ./docker/db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - "127.0.0.1:${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:?MYSQL_PASSWORD is not set or empty}
      - MYSQL_RANDOM_ROOT_PASSWORD='1'
      - MYSQL_USER=${MYSQL_USER:-nextcloud}

  redis:
    build:
      context: ./docker/redis
    restart: always
    environment:
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD:-!ChangeMe!}

volumes:
  php_socket:
